David noserver
credentials/irma_js pull request #6
Opened 2018-05-22 09:53 UTC by davidv1992

Removed need for a server component in irma_js

2018-05-22 14:26 UTC, sietseringers commented on Gruntfile.js
> +    var server_url, api_server_url;
Now that the `web_server_url` parameter is gone, the `server_url` should go too (its purpose was to enable the user to provide one base url for the `web_server_url` and `api_server_url`).

2018-05-22 15:24 UTC, confiks requested changes
Er zit één vraag tussen over het gebruik van `kjua`, en verder zijn het vooral nitpicks.

2018-05-22 15:24 UTC, confiks commented on client/irma.js
> +        xhr.send();
Hoewel dit een heel klein geval is, zou ik niet jQuery AJAX en rauwe XMLHttpRequest door elkaar gebruiken. Stick to a single interface. De indentation (in alle calls op instance methods van `xhr`) is ook niet consistent met de rest van de code.

2018-05-22 15:24 UTC, confiks commented on client/irma.js
> +var kjua = require("kjua");
Waarom heb je gekozen voor de `kjua` library, en niet voor bijvoorbeeld battle-tested `node-qrcode`? `kjua` lijkt vooral gemaakt te zijn voor fancy QR codes met plaatjes en afgeronde hoeken, wordt niet echt veel gebruikt en is volgens mij niet maintained (de laatste commit is welliswaar van 24 dagen geleden, maar dat zijn enkel package upgrades).

2018-05-22 15:24 UTC, confiks commented on client/irma.js
> +const PopupStrings = {
Gebruikt title-case i.p.v. camel-case als naam. (De andere variabelen die al title-case waren zouden eigenlijk ook gewoon camel-case moeten zijn)

2018-05-22 15:24 UTC, confiks commented on client/irma.js
> +const IrmaLogo = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKAAAACACAYAAACMY2IbAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3wsPDBsAoCMX4wAAFxpJREFUeNrtnXucHFWVx7+3qrrnPZNM3pV
Gebruikt title-case i.p.v. camel-case als naam. Zou dit niet beter in een aparte file kunnen? Ik neem aan dat je gekozen hebt voor een base64-encoded PNG omdat de user anders een apart bestand zou moeten fetchen. Misschien dat het build-proces hier niet zo geschikt voor is though.

2018-05-24 11:43 UTC, sietseringers commented on README.md
De `--server` vlag bestaat niet meer.

2018-05-24 14:33 UTC, sietseringers commented on client/irma.js
> +
Superfluous whitespace on empty line (elsewhere too)

2018-05-24 14:34 UTC, sietseringers commented on client/irma.js
> +        $("#irma-server-modal .irma_title").text(serverPage.Title);
We should consistently use either dashes or underscores for HTML classes and id's (I prefer dashes).

2018-05-24 14:35 UTC, sietseringers commented on client/irma.js
> +const IrmaLogo = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKAAAACACAYAAACMY2IbAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3wsPDBsAoCMX4wAAFxpJREFUeNrtnXucHFWVx7+3qrrnPZNM3pV
Er mist een `;` aan het eind van deze regel.

2018-05-24 14:35 UTC, sietseringers commented on client/irma.js
> +        })
`;` missing

2018-05-25 08:38 UTC, merged